path: /Users/alvinsonny/Desktop/drishti-kavach/dataset_rail-drishti
train: images/train
val: images/val
names:
  0: Rail_Track_Bed
  1: Rail_Lines
  2: Person
  3: Car
  4: Truck
  5: Branch
  6: IronRod
  7: Barrel
  8: Boulder
  9: Jerrycan
