path: dataset_rail-drishti
train: images/train
val: images/val
names:
  0: Rail_Track_Bed
  1: Rail_Lines
  2: Branch
  3: IronRod
  4: Barrel
  5: Boulder
  6: Jerrycan
  7: Person
  8: Cattle
  9: Animal
  10: Vehicle
